//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/ClientAndGC.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: ProtoBuffer/ClientAndGCCmd.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
}