//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/ClientAndLoginCmd.proto
// Note: requires additional types generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
    [global::ProtoBuf.ProtoContract(Name=@"CLIToLGIProtocol")]
    public enum CLIToLGIProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_PROTOCOL_BEGIN", Value=1)]
      CLI_TO_LGI_PROTOCOL_BEGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_PING", Value=2)]
      CLI_TO_LGI_PING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_CHECK_VERSION", Value=3)]
      CLI_TO_LGI_CHECK_VERSION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_ACCOUNT_LOGIN", Value=4)]
      CLI_TO_LGI_ACCOUNT_LOGIN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_RECONNECT", Value=5)]
      CLI_TO_LGI_RECONNECT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_LOGOUT", Value=6)]
      CLI_TO_LGI_LOGOUT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_QUERY_INFO", Value=7)]
      CLI_TO_LGI_QUERY_INFO = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_ENTER_GAME", Value=8)]
      CLI_TO_LGI_ENTER_GAME = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_EXIT_GAME", Value=9)]
      CLI_TO_LGI_EXIT_GAME = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_CREATE_ROOM", Value=10)]
      CLI_TO_LGI_CREATE_ROOM = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_ENTER_ROOM", Value=11)]
      CLI_TO_LGI_ENTER_ROOM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_EXIT_ROOM", Value=12)]
      CLI_TO_LGI_EXIT_ROOM = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_CHAT_MESAGE", Value=13)]
      CLI_TO_LGI_CHAT_MESAGE = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_MJ_GAME_OP", Value=14)]
      CLI_TO_LGI_MJ_GAME_OP = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_NN_GAME_OP", Value=15)]
      CLI_TO_LGI_NN_GAME_OP = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_SG_GAME_OP", Value=16)]
      CLI_TO_LGI_SG_GAME_OP = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_POKER_GAME_OP", Value=17)]
      CLI_TO_LGI_POKER_GAME_OP = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGL_MT_GAME_LUCK", Value=18)]
      CLI_TO_LGL_MT_GAME_LUCK = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGL_MJ_GAME_SOCE", Value=19)]
      CLI_TO_LGL_MJ_GAME_SOCE = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGL_MJ_GAME_TASK", Value=20)]
      CLI_TO_LGL_MJ_GAME_TASK = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGL_MJ_GAME_SHARE", Value=21)]
      CLI_TO_LGL_MJ_GAME_SHARE = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGL_GAME_EXCHANGE", Value=22)]
      CLI_TO_LGL_GAME_EXCHANGE = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_ONLINE_CHECK", Value=23)]
      CLI_TO_LGI_ONLINE_CHECK = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_SHARE", Value=24)]
      CLI_TO_LGI_SHARE = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_REDIRECT_CENTERSERVER", Value=98)]
      CLI_TO_LGI_REDIRECT_CENTERSERVER = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_PROTOCOL_COUNT", Value=99)]
      CLI_TO_LGI_PROTOCOL_COUNT = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLI_TO_LGI_PROTOCOL_END", Value=100)]
      CLI_TO_LGI_PROTOCOL_END = 100
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LGIToCLIProtocol")]
    public enum LGIToCLIProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_PROTOCOL_BEGIN", Value=1)]
      LGI_TO_CLI_PROTOCOL_BEGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_CHECK_VERSION", Value=2)]
      LGI_TO_CLI_CHECK_VERSION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_ACCOUNT_LOGIN", Value=3)]
      LGI_TO_CLI_ACCOUNT_LOGIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_RECONNECT", Value=4)]
      LGI_TO_CLI_RECONNECT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_NOTIFY_MESSAGE", Value=5)]
      LGI_TO_CLI_NOTIFY_MESSAGE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_QUERY_INFO", Value=6)]
      LGI_TO_CLI_QUERY_INFO = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_ENTER_GAME", Value=10)]
      LGI_TO_CLI_ENTER_GAME = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_EXIT_GAME", Value=11)]
      LGI_TO_CLI_EXIT_GAME = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_CREATE_ROOM", Value=12)]
      LGI_TO_CLI_CREATE_ROOM = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_ENTER_ROOM", Value=13)]
      LGI_TO_CLI_ENTER_ROOM = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_EXIT_ROOM", Value=14)]
      LGI_TO_CLI_EXIT_ROOM = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_CHAT_MESAGE", Value=15)]
      LGI_TO_CLI_CHAT_MESAGE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_ROOM_INFO", Value=16)]
      LGI_TO_CLI_ROOM_INFO = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_MJ_HAND_CARDS", Value=17)]
      LGI_TO_CLI_MJ_HAND_CARDS = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_MJ_ASK_GAME_OP", Value=18)]
      LGI_TO_CLI_MJ_ASK_GAME_OP = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_MJ_NOTIFY_GAME_OP", Value=19)]
      LGI_TO_CLI_MJ_NOTIFY_GAME_OP = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_MJ_GAME_OVER", Value=20)]
      LGI_TO_CLI_MJ_GAME_OVER = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_NN_HAND_CARDS", Value=21)]
      LGI_TO_CLI_NN_HAND_CARDS = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_NN_ASK_GAME_OP", Value=22)]
      LGI_TO_CLI_NN_ASK_GAME_OP = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_NN_NOTIFY_GAME_OP", Value=23)]
      LGI_TO_CLI_NN_NOTIFY_GAME_OP = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_NN_GAME_OVER", Value=24)]
      LGI_TO_CLI_NN_GAME_OVER = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_SG_HAND_CARDS", Value=25)]
      LGI_TO_CLI_SG_HAND_CARDS = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_SG_ASK_GAME_OP", Value=26)]
      LGI_TO_CLI_SG_ASK_GAME_OP = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_SG_NOTIFY_GAME_OP", Value=27)]
      LGI_TO_CLI_SG_NOTIFY_GAME_OP = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_SG_GAME_OVER", Value=28)]
      LGI_TO_CLI_SG_GAME_OVER = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_POKER_HAND_CARDS", Value=29)]
      LGI_TO_CLI_POKER_HAND_CARDS = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_POKER_ASK_GAME_OP", Value=30)]
      LGI_TO_CLI_POKER_ASK_GAME_OP = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_POKER_NOTIFY_GAME_OP", Value=31)]
      LGI_TO_CLI_POKER_NOTIFY_GAME_OP = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_POKER_GAME_OVER", Value=32)]
      LGI_TO_CLI_POKER_GAME_OVER = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_LGL_MT_GAME_LUCK", Value=33)]
      LGI_TO_LGL_MT_GAME_LUCK = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGL_TO_LGL_MJ_GAME_SOCE", Value=34)]
      LGL_TO_LGL_MJ_GAME_SOCE = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGL_TO_CLI_MJ_GAME_TASK", Value=35)]
      LGL_TO_CLI_MJ_GAME_TASK = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGL_TO_CLI_GAME_EXCHANGE", Value=36)]
      LGL_TO_CLI_GAME_EXCHANGE = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_PING", Value=37)]
      LGI_TO_CLI_PING = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_SHARE", Value=38)]
      LGI_TO_CLI_SHARE = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_PROTOCOL_COUNT", Value=99)]
      LGI_TO_CLI_PROTOCOL_COUNT = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LGI_TO_CLI_PROTOCOL_END", Value=100)]
      LGI_TO_CLI_PROTOCOL_END = 100
    }
  
}