//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private uint _charId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterState")]
  public partial class CharacterState : global::ProtoBuf.IExtensible
  {
    public CharacterState() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _isQZ = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isQZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isQZ
    {
      get { return _isQZ; }
      set { _isQZ = value; }
    }
    private uint _isZB = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isZB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isZB
    {
      get { return _isZB; }
      set { _isZB = value; }
    }
    private uint _isFangQiQZ = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isFangQiQZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isFangQiQZ
    {
      get { return _isFangQiQZ; }
      set { _isFangQiQZ = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _restGold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"restGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restGold
    {
      get { return _restGold; }
      set { _restGold = value; }
    }
    private int _restDiamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"restDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restDiamond
    {
      get { return _restDiamond; }
      set { _restDiamond = value; }
    }
    private uint _endSort = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"endSort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endSort
    {
      get { return _endSort; }
      set { _endSort = value; }
    }
    private uint _friendId = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
    private float _longitude = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"longitude", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float longitude
    {
      get { return _longitude; }
      set { _longitude = value; }
    }
    private float _latitude = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"latitude", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float latitude
    {
      get { return _latitude; }
      set { _latitude = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XZDDRule")]
  public partial class XZDDRule : global::ProtoBuf.IExtensible
  {
    public XZDDRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD> _flags = new global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD>();
    [global::ProtoBuf.ProtoMember(1, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD> flags
    {
      get { return _flags; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"XZDD")]
    public enum XZDD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJD", Value=1)]
      ZMJD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DYJJD", Value=3)]
      DYJJD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H3Z", Value=4)]
      H3Z = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_ZM", Value=5)]
      DGH_ZM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_FP", Value=6)]
      DGH_FP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TDH", Value=7)]
      TDH = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MQZZ", Value=8)]
      MQZZ = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HJZY", Value=9)]
      HJZY = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChampionPay", Value=10)]
      ChampionPay = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XLCHRule")]
  public partial class XLCHRule : global::ProtoBuf.IExtensible
  {
    public XLCHRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH> _xlch = new global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH>();
    [global::ProtoBuf.ProtoMember(1, Name=@"xlch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH> xlch
    {
      get { return _xlch; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"XLCH")]
    public enum XLCH
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJD", Value=1)]
      ZMJD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DYJJD", Value=3)]
      DYJJD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H3Z", Value=4)]
      H3Z = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_ZM", Value=5)]
      DGH_ZM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_FP", Value=6)]
      DGH_FP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TDH", Value=7)]
      TDH = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DDHRule")]
  public partial class DDHRule : global::ProtoBuf.IExtensible
  {
    public DDHRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH> _ddh = new global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ddh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH> ddh
    {
      get { return _ddh; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DDH")]
    public enum DDH
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DPH", Value=1)]
      DPH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMH", Value=2)]
      ZMH = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GARule")]
  public partial class GARule : global::ProtoBuf.IExtensible
  {
    public GARule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.GARule.GA> _ga = new global::System.Collections.Generic.List<ProtoBuf.GARule.GA>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ga", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.GARule.GA> ga
    {
      get { return _ga; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"GA")]
    public enum GA
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OGM", Value=1)]
      OGM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NGM", Value=2)]
      NGM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BZFJ", Value=3)]
      BZFJ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZP", Value=4)]
      ZP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DQ", Value=5)]
      DQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MD", Value=6)]
      MD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DJ", Value=7)]
      DJ = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GDGARule")]
  public partial class GDGARule : global::ProtoBuf.IExtensible
  {
    public GDGARule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.GDGARule.GDGA> _gdga = new global::System.Collections.Generic.List<ProtoBuf.GDGARule.GDGA>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gdga", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.GDGARule.GDGA> gdga
    {
      get { return _gdga; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private ProtoBuf.GlodLevel _gdlevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gdlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GlodLevel gdlevel
    {
      get { return _gdlevel; }
      set { _gdlevel = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"GDGA")]
    public enum GDGA
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OGM", Value=1)]
      OGM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NGM", Value=2)]
      NGM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BZFJ", Value=3)]
      BZFJ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZP", Value=4)]
      ZP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DQ", Value=5)]
      DQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MD", Value=6)]
      MD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DJ", Value=7)]
      DJ = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GDMJRule")]
  public partial class GDMJRule : global::ProtoBuf.IExtensible
  {
    public GDMJRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.GDMJRule.GDMJ> _flags = new global::System.Collections.Generic.List<ProtoBuf.GDMJRule.GDMJ>();
    [global::ProtoBuf.ProtoMember(1, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.GDMJRule.GDMJ> flags
    {
      get { return _flags; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private ProtoBuf.GlodLevel _gdlevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gdlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GlodLevel gdlevel
    {
      get { return _gdlevel; }
      set { _gdlevel = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"GDMJ")]
    public enum GDMJ
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJD", Value=1)]
      ZMJD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DYJJD", Value=3)]
      DYJJD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H3Z", Value=4)]
      H3Z = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_ZM", Value=5)]
      DGH_ZM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_FP", Value=6)]
      DGH_FP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TDH", Value=7)]
      TDH = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MQZZ", Value=8)]
      MQZZ = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerRule")]
  public partial class PokerRule : global::ProtoBuf.IExtensible
  {
    public PokerRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.PokerRule.Poker> _pokerrules = new global::System.Collections.Generic.List<ProtoBuf.PokerRule.Poker>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pokerrules", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.PokerRule.Poker> pokerrules
    {
      get { return _pokerrules; }
    }
  
    private uint _baseScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"baseScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint baseScore
    {
      get { return _baseScore; }
      set { _baseScore = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Poker")]
    public enum Poker
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PingJuDouble", Value=1)]
      PingJuDouble = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QiangFirst", Value=2)]
      QiangFirst = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YiTiaoLong", Value=3)]
      YiTiaoLong = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChampionPay", Value=4)]
      ChampionPay = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomRuleInfo")]
  public partial class MJRoomRuleInfo : global::ProtoBuf.IExtensible
  {
    public MJRoomRuleInfo() {}
    
    private ProtoBuf.MJRoomRule _gameRule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.MJRoomRule gameRule
    {
      get { return _gameRule; }
      set { _gameRule = value; }
    }
    private ProtoBuf.XZDDRule _xzddRule = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xzddRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.XZDDRule xzddRule
    {
      get { return _xzddRule; }
      set { _xzddRule = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerRoomRuleInfo")]
  public partial class PokerRoomRuleInfo : global::ProtoBuf.IExtensible
  {
    public PokerRoomRuleInfo() {}
    
    private ProtoBuf.PokerRoomRule _gameRule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.PokerRoomRule gameRule
    {
      get { return _gameRule; }
      set { _gameRule = value; }
    }
    private ProtoBuf.PokerRule _pokerRule = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pokerRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.PokerRule pokerRule
    {
      get { return _pokerRule; }
      set { _pokerRule = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJCardsInfo")]
  public partial class MJCardsInfo : global::ProtoBuf.IExtensible
  {
    public MJCardsInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _pengCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"pengCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> pengCards
    {
      get { return _pengCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _mingGangCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"mingGangCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mingGangCards
    {
      get { return _mingGangCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _anGangCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"anGangCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> anGangCards
    {
      get { return _anGangCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _huCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"huCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huCards
    {
      get { return _huCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _passCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"passCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> passCards
    {
      get { return _passCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zOut = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"x3zOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zOut
    {
      get { return _x3zOut; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zIn = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"x3zIn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zIn
    {
      get { return _x3zIn; }
    }
  
    private ProtoBuf.MJCardType _xQue = ProtoBuf.MJCardType.MJ_CARD_TYPE_WAN;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"xQue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoBuf.MJCardType.MJ_CARD_TYPE_WAN)]
    public ProtoBuf.MJCardType xQue
    {
      get { return _xQue; }
      set { _xQue = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _tingCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"tingCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> tingCards
    {
      get { return _tingCards; }
    }
  
    private bool _hasBaoTing = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hasBaoTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool hasBaoTing
    {
      get { return _hasBaoTing; }
      set { _hasBaoTing = value; }
    }
    private uint _roundRestCardNum = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"roundRestCardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roundRestCardNum
    {
      get { return _roundRestCardNum; }
      set { _roundRestCardNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomCacheChar")]
  public partial class MJRoomCacheChar : global::ProtoBuf.IExtensible
  {
    public MJRoomCacheChar() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oriCharId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oriCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oriCharId
    {
      get { return _oriCharId; }
      set { _oriCharId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _opList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"opList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> opList
    {
      get { return _opList; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _cardList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cardList
    {
      get { return _cardList; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _gangList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"gangList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> gangList
    {
      get { return _gangList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomCaching")]
  public partial class MJRoomCaching : global::ProtoBuf.IExtensible
  {
    public MJRoomCaching() {}
    
    private readonly global::System.Collections.Generic.List<uint> _huCharIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"huCharIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huCharIds
    {
      get { return _huCharIds; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _huTypes = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"huTypes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huTypes
    {
      get { return _huTypes; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar> _charList = new global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar>();
    [global::ProtoBuf.ProtoMember(3, Name=@"charList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar> charList
    {
      get { return _charList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomInfo")]
  public partial class MJRoomInfo : global::ProtoBuf.IExtensible
  {
    public MJRoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.MJRoomRuleInfo _roomRuleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRuleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.MJRoomRuleInfo roomRuleInfo
    {
      get { return _roomRuleInfo; }
      set { _roomRuleInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo> _cardsInfos = new global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo> cardsInfos
    {
      get { return _cardsInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> _charInfos = new global::System.Collections.Generic.List<ProtoBuf.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"charInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> charInfos
    {
      get { return _charInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _charIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"charIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIds
    {
      get { return _charIds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterState> _charStates = new global::System.Collections.Generic.List<ProtoBuf.CharacterState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"charStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterState> charStates
    {
      get { return _charStates; }
    }
  
    private uint _zjId = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zjId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zjId
    {
      get { return _zjId; }
      set { _zjId = value; }
    }
    private uint _inGame = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"inGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inGame
    {
      get { return _inGame; }
      set { _inGame = value; }
    }
    private ProtoBuf.MJRoomCaching _roomCache = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"roomCache", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.MJRoomCaching roomCache
    {
      get { return _roomCache; }
      set { _roomCache = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _agreedCharId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"agreedCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> agreedCharId
    {
      get { return _agreedCharId; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _disagreedCharId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"disagreedCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> disagreedCharId
    {
      get { return _disagreedCharId; }
    }
  
    private uint _restNum = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"restNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint restNum
    {
      get { return _restNum; }
      set { _restNum = value; }
    }
    private uint _maxRoundNum = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"maxRoundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxRoundNum
    {
      get { return _maxRoundNum; }
      set { _maxRoundNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachPBPlayer")]
  public partial class EachPBPlayer : global::ProtoBuf.IExtensible
  {
    public EachPBPlayer() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private uint _queType = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"queType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint queType
    {
      get { return _queType; }
      set { _queType = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _x3zCardIn = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"x3zCardIn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zCardIn
    {
      get { return _x3zCardIn; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zCardOut = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"x3zCardOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zCardOut
    {
      get { return _x3zCardOut; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachPBPlayerOP")]
  public partial class EachPBPlayerOP : global::ProtoBuf.IExtensible
  {
    public EachPBPlayerOP() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oricharId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"oricharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oricharId
    {
      get { return _oricharId; }
      set { _oricharId = value; }
    }
    private ProtoBuf.MJGameOP _op;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.MJGameOP op
    {
      get { return _op; }
      set { _op = value; }
    }
    private uint _card = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _rest = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rest
    {
      get { return _rest; }
      set { _rest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJPlayBack")]
  public partial class MJPlayBack : global::ProtoBuf.IExtensible
  {
    public MJPlayBack() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP> _opInfo = new global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP>();
    [global::ProtoBuf.ProtoMember(4, Name=@"opInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP> opInfo
    {
      get { return _opInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QPEachPBPlayer")]
  public partial class QPEachPBPlayer : global::ProtoBuf.IExtensible
  {
    public QPEachPBPlayer() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QPEachPBPlayerOP")]
  public partial class QPEachPBPlayerOP : global::ProtoBuf.IExtensible
  {
    public QPEachPBPlayerOP() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oricharId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"oricharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oricharId
    {
      get { return _oricharId; }
      set { _oricharId = value; }
    }
    private ProtoBuf.PokerGameOP _op;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.PokerGameOP op
    {
      get { return _op; }
      set { _op = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _cards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QPPlayBack")]
  public partial class QPPlayBack : global::ProtoBuf.IExtensible
  {
    public QPPlayBack() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayer> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayerOP> _opInfo = new global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayerOP>();
    [global::ProtoBuf.ProtoMember(4, Name=@"opInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.QPEachPBPlayerOP> opInfo
    {
      get { return _opInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachRoundPlayer")]
  public partial class EachRoundPlayer : global::ProtoBuf.IExtensible
  {
    public EachRoundPlayer() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private int _restGold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"restGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restGold
    {
      get { return _restGold; }
      set { _restGold = value; }
    }
    private int _restDiamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"restDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restDiamond
    {
      get { return _restDiamond; }
      set { _restDiamond = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoundRecord")]
  public partial class MJRoundRecord : global::ProtoBuf.IExtensible
  {
    public MJRoundRecord() {}
    
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private ulong _roundOverTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundOverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roundOverTime
    {
      get { return _roundOverTime; }
      set { _roundOverTime = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> players
    {
      get { return _players; }
    }
  
    private ProtoBuf.MJPlayBack _playBack = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playBack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.MJPlayBack playBack
    {
      get { return _playBack; }
      set { _playBack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomRecord")]
  public partial class MJRoomRecord : global::ProtoBuf.IExtensible
  {
    public MJRoomRecord() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord> _rounds = new global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord> rounds
    {
      get { return _rounds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharFriend")]
  public partial class CharFriend : global::ProtoBuf.IExtensible
  {
    public CharFriend() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private float _winRate = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"winRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float winRate
    {
      get { return _winRate; }
      set { _winRate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharFriendList")]
  public partial class CharFriendList : global::ProtoBuf.IExtensible
  {
    public CharFriendList() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharFriend> _friendList = new global::System.Collections.Generic.List<ProtoBuf.CharFriend>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharFriend> friendList
    {
      get { return _friendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharInfoDync")]
  public partial class CharInfoDync : global::ProtoBuf.IExtensible
  {
    public CharInfoDync() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _param1 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _param2 = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _param3 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }
    private int _param4 = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"param4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param4
    {
      get { return _param4; }
      set { _param4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QPRoundRecord")]
  public partial class QPRoundRecord : global::ProtoBuf.IExtensible
  {
    public QPRoundRecord() {}
    
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private ulong _roundOverTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundOverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roundOverTime
    {
      get { return _roundOverTime; }
      set { _roundOverTime = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> players
    {
      get { return _players; }
    }
  
    private ProtoBuf.QPPlayBack _playBack = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playBack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.QPPlayBack playBack
    {
      get { return _playBack; }
      set { _playBack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QPRoomRecord")]
  public partial class QPRoomRecord : global::ProtoBuf.IExtensible
  {
    public QPRoomRecord() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.QPRoundRecord> _rounds = new global::System.Collections.Generic.List<ProtoBuf.QPRoundRecord>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.QPRoundRecord> rounds
    {
      get { return _rounds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerOpInfo")]
  public partial class PokerOpInfo : global::ProtoBuf.IExtensible
  {
    public PokerOpInfo() {}
    
    private uint _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint op
    {
      get { return _op; }
      set { _op = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _cards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cards
    {
      get { return _cards; }
    }
  
    private ProtoBuf.PokerGameOP _lastOp = ProtoBuf.PokerGameOP.Poker_OP_NULL;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastOp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoBuf.PokerGameOP.Poker_OP_NULL)]
    public ProtoBuf.PokerGameOP lastOp
    {
      get { return _lastOp; }
      set { _lastOp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerRoomCacheChar")]
  public partial class PokerRoomCacheChar : global::ProtoBuf.IExtensible
  {
    public PokerRoomCacheChar() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oriCharId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oriCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oriCharId
    {
      get { return _oriCharId; }
      set { _oriCharId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.PokerOpInfo> _opInfo = new global::System.Collections.Generic.List<ProtoBuf.PokerOpInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"opInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.PokerOpInfo> opInfo
    {
      get { return _opInfo; }
    }
  
    private uint _endSort = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endSort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endSort
    {
      get { return _endSort; }
      set { _endSort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerRoomCaching")]
  public partial class PokerRoomCaching : global::ProtoBuf.IExtensible
  {
    public PokerRoomCaching() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.PokerRoomCacheChar> _charList = new global::System.Collections.Generic.List<ProtoBuf.PokerRoomCacheChar>();
    [global::ProtoBuf.ProtoMember(1, Name=@"charList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.PokerRoomCacheChar> charList
    {
      get { return _charList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerRoomInfo")]
  public partial class PokerRoomInfo : global::ProtoBuf.IExtensible
  {
    public PokerRoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.PokerRoomRuleInfo _roomRuleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRuleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.PokerRoomRuleInfo roomRuleInfo
    {
      get { return _roomRuleInfo; }
      set { _roomRuleInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.PokerCardsInfo> _cardsInfos = new global::System.Collections.Generic.List<ProtoBuf.PokerCardsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.PokerCardsInfo> cardsInfos
    {
      get { return _cardsInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> _charInfos = new global::System.Collections.Generic.List<ProtoBuf.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"charInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> charInfos
    {
      get { return _charInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _charIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"charIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIds
    {
      get { return _charIds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterState> _charStates = new global::System.Collections.Generic.List<ProtoBuf.CharacterState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"charStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterState> charStates
    {
      get { return _charStates; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _lastChuCard = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"lastChuCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> lastChuCard
    {
      get { return _lastChuCard; }
    }
  
    private uint _zjId = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"zjId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zjId
    {
      get { return _zjId; }
      set { _zjId = value; }
    }
    private uint _inGame = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"inGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inGame
    {
      get { return _inGame; }
      set { _inGame = value; }
    }
    private ProtoBuf.PokerRoomCaching _roomCache = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"roomCache", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.PokerRoomCaching roomCache
    {
      get { return _roomCache; }
      set { _roomCache = value; }
    }
    private uint _qiangId = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"qiangId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint qiangId
    {
      get { return _qiangId; }
      set { _qiangId = value; }
    }
    private uint _shoutCard = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shoutCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shoutCard
    {
      get { return _shoutCard; }
      set { _shoutCard = value; }
    }
    private uint _roundTh;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"roundTh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundTh
    {
      get { return _roundTh; }
      set { _roundTh = value; }
    }
    private uint _ownerId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"ownerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ownerId
    {
      get { return _ownerId; }
      set { _ownerId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _agreedCharId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(15, Name=@"agreedCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> agreedCharId
    {
      get { return _agreedCharId; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _disagreedCharId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(16, Name=@"disagreedCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> disagreedCharId
    {
      get { return _disagreedCharId; }
    }
  
    private uint _nextCharId = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"nextCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint nextCharId
    {
      get { return _nextCharId; }
      set { _nextCharId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerCardsInfo")]
  public partial class PokerCardsInfo : global::ProtoBuf.IExtensible
  {
    public PokerCardsInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _passCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"passCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> passCards
    {
      get { return _passCards; }
    }
  
    private bool _hasBaoTing = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hasBaoTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool hasBaoTing
    {
      get { return _hasBaoTing; }
      set { _hasBaoTing = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _getCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"getCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> getCards
    {
      get { return _getCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _curChuCard = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"curChuCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> curChuCard
    {
      get { return _curChuCard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PROTOCOL_VERSION_UPPER")]
    public enum PROTOCOL_VERSION_UPPER
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTOCOL_VERSION_CURRENT", Value=1)]
      PROTOCOL_VERSION_CURRENT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PROTOCOL_VERSION_LOWER")]
    public enum PROTOCOL_VERSION_LOWER
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTOCOL_VERSION_LOWER_LIMIT", Value=1)]
      PROTOCOL_VERSION_LOWER_LIMIT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERetCode")]
    public enum ERetCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_SUCCESS", Value=0)]
      RET_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_FAIL", Value=1)]
      RET_FAIL = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PingConfig")]
    public enum PingConfig
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_PING_INTERVAL", Value=9)]
      CLIENT_PING_INTERVAL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_PING_INTERVAL", Value=9)]
      SERVER_PING_INTERVAL = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameType")]
    public enum GameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_NULL", Value=0)]
      GT_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_GC", Value=1)]
      GT_GC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_MJ", Value=2)]
      GT_MJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_Poker", Value=8)]
      GT_Poker = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJCardType")]
    public enum MJCardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_WAN", Value=1)]
      MJ_CARD_TYPE_WAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_TONG", Value=2)]
      MJ_CARD_TYPE_TONG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_TIAO", Value=3)]
      MJ_CARD_TYPE_TIAO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_FENG", Value=4)]
      MJ_CARD_TYPE_FENG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_ZI", Value=5)]
      MJ_CARD_TYPE_ZI = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_HUA", Value=6)]
      MJ_CARD_TYPE_HUA = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJRoomRule")]
    public enum MJRoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_XZDD", Value=1)]
      MJ_ROOM_RULE_XZDD = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PokerRoomRule")]
    public enum PokerRoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"POKER_ROOM_RULE", Value=1)]
      POKER_ROOM_RULE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJOPErrorCode")]
    public enum MJOPErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_1", Value=1)]
      MJ_OP_ERROR_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_2", Value=2)]
      MJ_OP_ERROR_2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_3", Value=3)]
      MJ_OP_ERROR_3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_4", Value=4)]
      MJ_OP_ERROR_4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_5", Value=5)]
      MJ_OP_ERROR_5 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_6", Value=6)]
      MJ_OP_ERROR_6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_7", Value=7)]
      MJ_OP_ERROR_7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_8", Value=8)]
      MJ_OP_ERROR_8 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_9", Value=9)]
      MJ_OP_ERROR_9 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_10", Value=10)]
      MJ_OP_ERROR_10 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_11", Value=11)]
      MJ_OP_ERROR_11 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_12", Value=12)]
      MJ_OP_ERROR_12 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_13", Value=13)]
      MJ_OP_ERROR_13 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_14", Value=14)]
      MJ_OP_ERROR_14 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_15", Value=15)]
      MJ_OP_ERROR_15 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_16", Value=16)]
      MJ_OP_ERROR_16 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_17", Value=17)]
      MJ_OP_ERROR_17 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_18", Value=18)]
      MJ_OP_ERROR_18 = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_19", Value=19)]
      MJ_OP_ERROR_19 = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_20", Value=20)]
      MJ_OP_ERROR_20 = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PokerOPErrorCode")]
    public enum PokerOPErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_1", Value=1)]
      Poker_OP_ERROR_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_2", Value=2)]
      Poker_OP_ERROR_2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_3", Value=3)]
      Poker_OP_ERROR_3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_4", Value=4)]
      Poker_OP_ERROR_4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_5", Value=5)]
      Poker_OP_ERROR_5 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_6", Value=6)]
      Poker_OP_ERROR_6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_7", Value=7)]
      Poker_OP_ERROR_7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_8", Value=8)]
      Poker_OP_ERROR_8 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_9", Value=9)]
      Poker_OP_ERROR_9 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_10", Value=10)]
      Poker_OP_ERROR_10 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_11", Value=11)]
      Poker_OP_ERROR_11 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ERROR_12", Value=12)]
      Poker_OP_ERROR_12 = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJGameOP")]
    public enum MJGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_PREP", Value=1)]
      MJ_OP_PREP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ZJ", Value=2)]
      MJ_OP_ZJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_X3Z", Value=3)]
      MJ_OP_X3Z = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_XQ", Value=4)]
      MJ_OP_XQ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_MOPAI", Value=5)]
      MJ_OP_MOPAI = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_CHUPAI", Value=6)]
      MJ_OP_CHUPAI = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GUO", Value=7)]
      MJ_OP_GUO = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_PENG", Value=8)]
      MJ_OP_PENG = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG", Value=9)]
      MJ_OP_GANG = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG2", Value=10)]
      MJ_OP_GANG2 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG3", Value=11)]
      MJ_OP_GANG3 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG4", Value=12)]
      MJ_OP_GANG4 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_HU", Value=13)]
      MJ_OP_HU = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TING", Value=14)]
      MJ_OP_TING = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_X3Z_RESULT", Value=15)]
      MJ_OP_X3Z_RESULT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ROUND_OVER", Value=16)]
      MJ_OP_ROUND_OVER = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_VOTE_JSROOM", Value=17)]
      MJ_OP_VOTE_JSROOM = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_VOTE_RESULT", Value=18)]
      MJ_OP_VOTE_RESULT = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_QUERY_MULTIPLY", Value=19)]
      MJ_OP_QUERY_MULTIPLY = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ON_LINE", Value=20)]
      MJ_OP_ON_LINE = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_COORD", Value=21)]
      MJ_OP_COORD = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_PLAYER_OP_RESULT", Value=22)]
      MJ_PLAYER_OP_RESULT = 22
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GlodLevel")]
    public enum GlodLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INITIAL", Value=1)]
      INITIAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MIDDLE", Value=2)]
      MIDDLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SENIOR", Value=3)]
      SENIOR = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PokerGameOP")]
    public enum PokerGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_NULL", Value=1)]
      Poker_OP_NULL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_QP", Value=2)]
      Poker_OP_QP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_CHE", Value=3)]
      Poker_OP_CHE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_CHU", Value=4)]
      Poker_OP_CHU = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_YTL", Value=5)]
      Poker_OP_YTL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_GUO", Value=6)]
      Poker_OP_GUO = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_PREP", Value=7)]
      Poker_OP_PREP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_EXITROOM", Value=8)]
      Poker_OP_EXITROOM = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ROUND_OVER", Value=9)]
      Poker_OP_ROUND_OVER = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_VOTE_JSROOM", Value=10)]
      Poker_OP_VOTE_JSROOM = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_VOTE_RESULT", Value=11)]
      Poker_OP_VOTE_RESULT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ON_LINE", Value=12)]
      Poker_OP_ON_LINE = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_SHOUT", Value=13)]
      Poker_OP_SHOUT = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_PICK", Value=14)]
      Poker_OP_PICK = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_CHU_OVER", Value=15)]
      Poker_OP_CHU_OVER = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_ZJ", Value=16)]
      Poker_OP_ZJ = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_SHOW", Value=17)]
      Poker_OP_SHOW = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_COORD", Value=18)]
      Poker_OP_COORD = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poker_OP_RESULT", Value=19)]
      Poker_OP_RESULT = 19
    }
  
}