//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBuffer/ComProtocol.proto
// Note: requires additional types generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EmptyMessage")]
  public partial class EmptyMessage : global::ProtoBuf.IExtensible
  {
    public EmptyMessage() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterServiceRequest")]
  public partial class RegisterServiceRequest : global::ProtoBuf.IExtensible
  {
    public RegisterServiceRequest() {}
    
    private uint _service_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint service_type
    {
      get { return _service_type; }
      set { _service_type = value; }
    }
    private uint _group_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }
    private uint _service_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"service_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint service_id
    {
      get { return _service_id; }
      set { _service_id = value; }
    }
    private string _listen_ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"listen_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string listen_ip
    {
      get { return _listen_ip; }
      set { _listen_ip = value; }
    }
    private uint _listen_port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"listen_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint listen_port
    {
      get { return _listen_port; }
      set { _listen_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterDBBaseInfo")]
  public partial class CharacterDBBaseInfo : global::ProtoBuf.IExtensible
  {
    public CharacterDBBaseInfo() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private ulong _createTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private ulong _lastSaveTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lastSaveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong lastSaveTime
    {
      get { return _lastSaveTime; }
      set { _lastSaveTime = value; }
    }
    private ulong _onlineTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"onlineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong onlineTime
    {
      get { return _onlineTime; }
      set { _onlineTime = value; }
    }
    private ulong _loginTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"loginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong loginTime
    {
      get { return _loginTime; }
      set { _loginTime = value; }
    }
    private ulong _logoutTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"logoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong logoutTime
    {
      get { return _logoutTime; }
      set { _logoutTime = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private uint _winNum = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"winNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint winNum
    {
      get { return _winNum; }
      set { _winNum = value; }
    }
    private uint _lostNum = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"lostNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lostNum
    {
      get { return _lostNum; }
      set { _lostNum = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _friendList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(18, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> friendList
    {
      get { return _friendList; }
    }
  
    private uint _thegold = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"thegold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thegold
    {
      get { return _thegold; }
      set { _thegold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemProtoInfo")]
  public partial class ItemProtoInfo : global::ProtoBuf.IExtensible
  {
    public ItemProtoInfo() {}
    
    private uint _item_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _item_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterDBPackData")]
  public partial class CharacterDBPackData : global::ProtoBuf.IExtensible
  {
    public CharacterDBPackData() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> _itemList = new global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ItemProtoInfo> itemList
    {
      get { return _itemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterDBExtendData")]
  public partial class CharacterDBExtendData : global::ProtoBuf.IExtensible
  {
    public CharacterDBExtendData() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterDBInfo")]
  public partial class CharacterDBInfo : global::ProtoBuf.IExtensible
  {
    public CharacterDBInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private ProtoBuf.CharacterDBBaseInfo _baseData;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"baseData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.CharacterDBBaseInfo baseData
    {
      get { return _baseData; }
      set { _baseData = value; }
    }
    private ProtoBuf.CharacterDBPackData _itemData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CharacterDBPackData itemData
    {
      get { return _itemData; }
      set { _itemData = value; }
    }
    private ProtoBuf.CharacterDBExtendData _extendData = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extendData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.CharacterDBExtendData extendData
    {
      get { return _extendData; }
      set { _extendData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyMgrCli")]
  public partial class NotifyMgrCli : global::ProtoBuf.IExtensible
  {
    public NotifyMgrCli() {}
    
    private uint _dore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dore
    {
      get { return _dore; }
      set { _dore = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _tpye;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tpye", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tpye
    {
      get { return _tpye; }
      set { _tpye = value; }
    }
    private uint _charID = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"charID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charID
    {
      get { return _charID; }
      set { _charID = value; }
    }
    private string _channel_user_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channel_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string channel_user_id
    {
      get { return _channel_user_id; }
      set { _channel_user_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _gametype = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gametype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gametype
    {
      get { return _gametype; }
      set { _gametype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}